spring:
  application:
    name: timeoff
  datasource:
    url: jdbc:postgresql://localhost:5432/timeoff
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
