INSERT INTO employee (id, name, manager_id) VALUES
    (1, 'Manager One', null),
    (2, 'Manager Two', null),
    (3, 'A Aladar', 1),
    (4, 'B Bela', 1),
    (5, 'C Cecil', 1),
    (6, 'D Denes', 1),
    (7, 'E Elemer', 1),
    (8, 'F Ferenc', 1),
    (9, 'G Gergely', 1),
    (10, 'H Henrietta', 1),
    (11, 'I Ilona', 1),
    (12, 'J Julia', 1),
    (13, 'K Karoly', 2),
    (14, 'L Laszlo', 2),
    (15, 'M Miklos', 2),
    (16, 'N Noemi', 2),
    (17, 'O Odon', 2),
    (18, 'P Patrik', 2),
    (19, 'Q Qmittudomen', 2),
    (20, 'R Reka', 2),
    (21, 'S Sarolta', 2),
    (22, 'T Tibor', 2);

